# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Album' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Album
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  pod 'Stripe'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Nuke', '~> 5.0'
  pod 'Preheat', '~> 3.0'

  target 'AlbumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlbumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
